
type User {
	userName: String
	displayName: String
	mail: String
}

type DefaultResponse {
	message: String
}


type Query {
	users: [User]
}

type Mutation {
	insertAdminUser(userName: String!, displayName: String!, mail: String!, password: String!): DefaultResponse
}
